### ISSUE TITLE
provide example

### ISSUE THREAD

**Issue by marshonhuckleberry** [usimarit/TiramisuASR#10]
provide example in readme for quality evaluation, original text and recognised text (speak original text with your voice)

**Comment by usimarit** [comment]
I'll provide some evaluation examples in Vietnamese soon :smiley:. I haven't trained any models in English or other languages yet so I don't have any examples for those languages.
About speaking with my voice, I don't think my dataset covers enough voices in order for the model to perform well on my voice, but I'll include it anyway.

**Comment by usimarit** [comment]
I have provided some examples of `conformer` trained on librispeech 100h in this website: [huylenguyen.com/asr](https://huylenguyen.com/asr)
