### ISSUE TITLE
Setup: Could not find a version that satisfies the requirement ctc-decoders

### ISSUE THREAD

**Issue by stefan-falk** [usimarit/TiramisuASR#11]
Running `pip install .` after cloning the repository gives me:

```
ERROR: Could not find a version that satisfies the requirement ctc-decoders (from tiramisu-asr==0.0.1) (from versions: none)
ERROR: No matching distribution found for ctc-decoders (from tiramisu-asr==0.0.1)
```

How can I set this up correctly?

### Enrionment

```
$ python --version
Python 3.7.0
$ uname -sv
Linux #100~16.04.1-Ubuntu SMP Wed Apr 22 23:56:30 UTC 2020
```

**Comment by usimarit** [comment]
Sorry that I didn't write README properly. The repo of `ctc-decoders` is in the file `setup.sh`, you can install it manually :D
I'm working on NAN issue in Warp RNNT Loss so Transducer models are not ready yet. :(

**Comment by usimarit** [comment]
I updated README (include instructions for setting up env) and remove `ctc-decoders` from requirements so that we can install it manually if needed.

**Comment by usimarit** [comment]
The rnnt models are able to train now, and usage of the scripts to install external dependencies are specified in README. I'll close this here. Let me know if you have any other issues :D

**Comment by stefan-falk** [comment]
@usimarit Hello! Thanks for working on this! I'll give it a try as soon as I find the time. :)

**Comment by stefan-falk** [comment]
@usimarit Regarding the NAN issue: I had this issue too when I was using https://github.com/noahchalifour/rnnt-speech-recognition. I was Able to fix it though after following https://github.com/noahchalifour/rnnt-speech-recognition/issues/31#issuecomment-637499806 - not sure if that will help.

**Comment by usimarit** [comment]
> @usimarit Regarding the NAN issue: I had this issue too when I was using https://github.com/noahchalifour/rnnt-speech-recognition. I was Able to fix it though after following https://github.com/noahchalifour/rnnt-speech-recognition/issues/31#issuecomment-637499806 - not sure if that will help.
> 
> 

I had it because I was giving wrong `input_lengths`. The model reduces time dimension but I didnt reduce the `input_lengths` fed to rnnt_loss, therefore the time in `acts` and the `input_lengths mismatch, so it gave Nan values (and also output mismatch likelihood). I fixed it and it works now :laughing:

**Comment by stefan-falk** [comment]
Awesome! Thank you :)
