### ISSUE TITLE
Cannot access to dataset InfoRe 

### ISSUE THREAD

**Issue by ngoanpv** [usimarit/TiramisuASR#16]
Hi, 
I cannot access to dataset InfoRe. Could you please update the link?
Thank you!

**Comment by usimarit** [comment]
Hi @ngoanpv, 
My personal server is currently down (my laptop's charger is broken), therefore I cannot provide you the downloadable link for quite a while.
Also I don't have enough google drive storage to store the data.
I'm fixing the charger so please wait, I'll notify you when the server is up.

**Comment by ngoanpv** [comment]
Thanks for your information, 
I look forward to receiving your update!

**Comment by usimarit** [comment]
Hi @ngoanpv, the link is updated, I'm closing this here.

**Comment by ngoanpv** [comment]
Hi @usimarit, thanks for your update.
I cannot unzip those files because it has a password!
Could you provide the password?

**Comment by usimarit** [comment]
@ngoanpv, ah I forgot, it's `BroughtToYouByInfoRe`
