### ISSUE TITLE
Reshape error with tflite model

### ISSUE THREAD

**Issue by mapledxf** [usimarit/TiramisuASR#17]
I run the conformer model without any error.
But I got the following error when I run the tflite model with the same inputs.

```
RuntimeError: tensorflow/lite/kernels/reshape.cc:66 num_input_elements != num_output_elements (0 != 144)Node number 5 (RESHAPE) failed to prepare.
Node number 2840 (WHILE) failed to invoke.
```

Any idea why?

**Comment by mapledxf** [comment]
After I update the tf-nightly to the most recent version, I got following error:
```
RuntimeError: tensorflow/lite/kernels/reshape.cc:55 stretch_dim != -1 (0 != -1)Node number 187 (RESHAPE) failed to prepare.
```

**Comment by usimarit** [comment]
It's because tflite model doesn't support `tensor[index]`, so I have to use `tf.gather_nd` instead. I fixed this issue in master :D

**Comment by mapledxf** [comment]
It is all good now, thx!
The inference speed is a little bit slow, 
but it is an amazing project anyway!

**Comment by usimarit** [comment]
> It is all good now, thx!
> The inference speed is a little bit slow, 
> but it is an amazing project anyway!
> 

The beam search implementation is single thread so it's slow. I'm finding a way to improve it :D
