### ISSUE TITLE
Augmentation not working

### ISSUE THREAD

**Issue by ahsanmemon** [usimarit/TiramisuASR#24]
Augmentations giving this error (below). However, when I disable augmentation from config.yml file, the system works perfectly.
![image](https://user-images.githubusercontent.com/28605862/95113493-fa701580-075b-11eb-95ea-062417ec8bff.png)
Something that I am missing?

**Comment by usimarit** [comment]
@ahsanmemon You must generate `transcripts.tsv` files from LibriSpeech and change the paths in default `config.yml`.
The error says "Nonetype is not subscriptable", which means that the data fed to augmentation is None, you have to make sure there's data.
Recommended: the default `config.yml` is the example config file, it works only on my machine, you should create your own config file.

**Comment by ahsanmemon** [comment]
@usimarit , I did change the paths, and the transcripts.tsv files do exist I think. When I disabled the augmentations (shown in image below), the training started normally. (attaching image of it too)

![image](https://user-images.githubusercontent.com/28605862/95115118-62276000-075e-11eb-9447-a6aaf25488b4.png)
![image](https://user-images.githubusercontent.com/28605862/95115186-808d5b80-075e-11eb-98b5-d813a740bc5c.png)

**Comment by entn-at** [comment]
Try PR #26. It addresses this issue.

**Comment by ahsanmemon** [comment]
great. thanks. downgrading nlpaug to 0.0.14 solved the problem. closing.

**Comment by eashan2798** [comment]
Can you tell how to create the transcript.tsv files.Not able to get from where transcripts.tsv will generate?
