### ISSUE TITLE
Receiving forward-backward warning

### ISSUE THREAD

**Issue by ahsanmemon** [usimarit/TiramisuASR#25]
I am getting this warning. Is it okay to be getting this?

![image](https://user-images.githubusercontent.com/28605862/95115301-adda0980-075e-11eb-8353-4bf1537a21d5.png)

**Comment by usimarit** [comment]
No, when you get these warnings, you are doing wrong.
Did you run `conda install tensorflow-gpu`, specify `CUDA_HOME` and run `scripts/install_rnnt.sh` in the conda env?

**Comment by ahsanmemon** [comment]
Thanks for pointing it out. I had actually missed out on the CUDA_HOME part. After adding CUDA_HOME, the code is now working fine and I am getting positive losses.

Thanks
