### ISSUE TITLE
about mask in conformer?

### ISSUE THREAD

**Issue by alsm168** [usimarit/TiramisuASR#28]
hello，
I see the multi-head-attention have mask input in your code , but I can't find any code that generate the **mask**，Is this a bug?thank you  very much.

**Comment by usimarit** [comment]
I'm planning to support masking in every models, but now I haven't implemented masking so there's no code to generate **mask**. The mask in multi-head-attention will be used in the near future, for now you can ignore it.

**Comment by alsm168** [comment]
ok, thank you.  I'm looking forward to see.
