### ISSUE TITLE
InfoRe data is not available anymore

### ISSUE THREAD

**Issue by minhnb92** [usimarit/TiramisuASR#9]
Hi,

I have tried to download the InfoRe dataset with the torrent link provided in the Post shared by you. But there is no seed anymore so I cannot download it. Could you please share the dataset via Google Drive or other hosts?

Thank you in advance.

**Comment by usimarit** [comment]
I don't think I'm authorized to share that data publicly (those seeds are dead, which "might" mean that they do not want to share it anymore).
Let me contact the owner to ask if I can share that datasets and I'll let you know later.
In case they say I cannot, I can share them to you PRIVATELY via email or facebook (after I turn my server into torrent server).

**Comment by minhnb92** [comment]
Hi Huy,

many thanks for your reply and efforts to help me with the dataset. My email is nguyenbaminh1992@gmail.com. I am looking forward to hearing from you.

Best regards.

**Comment by usimarit** [comment]
Okay, give me some time to upload them to my server (56GB total) :D I'll share them to you tomorrow.

**Comment by usimarit** [comment]
Good news, they said that I can share the InfoRe datasets. Also, they said that they are refining and extending the datasets with other companies and they'll make those data public soon :D

**Comment by minhnb92** [comment]
Yay, thank you so much for your sharing :D If it is ok with you, could you share the current dataset with me tomorrow? I am really in need of it :)

**Comment by usimarit** [comment]
> Yay, thank you so much for your sharing :D If it is ok with you, could you share the current dataset with me tomorrow? I am really in need of it :)

Sorry, I have troubles with bittorrent and internet connection, therefore I still haven't upload the datasets to my VPS. I'm planning to create a downloadable link after the datasets are uploaded but I'm only available from this Sunday.
Could you wait a bit more? I'm really busy right now :(

**Comment by usimarit** [comment]
The datasets' links are updated, close issue here
